name = "carefone-mobile-shop"
main = "src/index.ts"
compatibility_date = "2025-12-27"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "carefone_db"
database_name = "carefone-db"
database_id = "f6d5d10a-b71d-4e83-a0a3-4fd1baca4b68"

[vars]
APP_ENV = "production"

[[durable_objects.bindings]]
name = "STAFF_TRACKER"
class_name = "StaffTracker"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["StaffTracker"]

[env.preview.vars]
APP_ENV = "preview"

[env.production.vars]
APP_ENV = "production"
